### ISSUE TITLE
Auto Validation at Render [HighLight grid cell]

### ISSUE THREAD

**Issue by RitivikaP** [cscan/vue-excel-editor#101]
Issue : I have a requirement wherein I upload a excel file. and perform validations as soon as upload button is clicked.The excel displayed during first render should automatically highlight cells with validation errors. However, "validate" gets triggered only when the excel data is manually edited by user.
To recreate this scenario during render, I tried setting error in grid data --
this.$refs.grid.value[0].err = 'Error Here'
I also tried manually emitting 'update' event after setting  above error -- this.$refs.grid.$emit('update',this.$refs.grid.value[0])
However, the grid cell still doesn't highlight the error in red.

Please provide teh solution for the same

**Comment by cscan** [comment]
I remember the doImport function will generate throw event if there is error when calling field validation() or row validation(). It also emits event importErrorCallback so that you can react the error by passing the callback function. However, the whole import will be stopped once error occured. It could not work as your expectation where you want to show multiple red triangle within cells for the error. I suggest you study the doImport function and write your own function to replace my default one. Hope this help.
