### ISSUE TITLE
Changing the column name

### ISSUE THREAD

**Issue by isjeffcom** [cscan/vue-excel-editor#52]
Which is the right way to update the data binding in v-model after user edit the column name? like this:

<img src="https://i.ibb.co/vLwqKFg/a.png" alt="a" border="0">

niow, the data from v-model still keep the same

<img src="https://i.ibb.co/Fz4GrCd/ccc.png" alt="ccc" border="0">

Thank you for this excellent library

**Comment by isjeffcom** [comment]
I assume this might explain better...

So I added a column and change the label of the new column

<img src="https://i.ibb.co/xXKLrwX/a.png" alt="a" border="0">

And I print the data binding in v-model

<img src="https://i.ibb.co/nn8V1pX/ccc.png" alt="ccc" border="0">

The column name remain as COL-5847

Is there anyway to update the data? I've tried to use @change in vue-excel-column, but it only fire when I change the row data, not the column label/field name.

**Comment by cscan** [comment]
You may specify the label in vue-excel-column for the column name. However, it will persist after mounted. If you want to change the column name after mounted, you may try the variable fields, something like this:

```js
this.$refs.grid.fields.forEach( (field) => {
   switch (field.name) {
      case 'COL-5847':
         field.label = 'My New Label'
         break
      ...
   }
   this.$forceUpdate()  // remember to call vue update to reflesh the display
})
```

**Comment by cscan** [comment]
Sorry, after I scanned your question again, seems you want to change back the v-model key after the column label changed. Let me explain in details. After the user changes a column label via the UI, the com will remember in localStorage if you specified remember prop via the following watch.

```js
    fields: {
      handler () {
        this.lazy(() => {
          const setting = this.getSetting()
          if (this.remember) localStorage[window.location.pathname + '.' + this.token] = JSON.stringify(setting)
          this.$emit('setting', setting)
        })
      },
      deep: true
    }
```

The saved labels and setting will be restored in the future. You can see the com will also fire a @setting event with an argument. Here is the formation of the argument:

```js
    getSetting () {
      const colWidth = Array.from(this.colgroupTr.children).map(col => col.style.width)
      const fields = this.fields.map((field, i) => {
        return {
          name: field.name,
          invisible: field.invisible,
          width: colWidth[i + 1],
          label: field.label
        }
      })
      return {
        colHash: this.colHash,
        fields: fields
      }
    },
```
You may get all the labels in argument.fields.label. However, if you want to change the key of the v-model, this is dangerous, since the com is using the key to map the column data, change the v-model key will make some column to disappear.

Hope this help.
